= Bases de Datos 1: Trabajo Práctico
== Primer Semestre 2023
v1, {docdate}. 
*Integrantes*

Buffagna Maria_Carla <mcarlabuff@gmail.com>; Curcio Matias <juanmatiascurcio@gmail.com>; Mendez Agustina <agustina.996@hotmail.com>

*Docentes*

Hernan Rondelli y Daniel Bertaccini

:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4


== Introducción

El siguiente trabajo consiste en un sistema para almacenar información relativa a la administración de turnos médicos.

El sistema permitirá asignar turnos, mantener toda la información de los pacientes, mediques, cobertura de las obras sociales, controlar que los turnos se asignen correctamente y administrar las liquidaciones
mensuales de las atenciones realizadas por cada medique.

// Para esto se creó una base de datos utilizando postgres y go //

== Descripción

Para comenzar, se agregaron las tablas:
*Paciente
*Medique
*Consultorio
*Obra social
Estas cuatro tablas guardaran informaciòn basica.
*Agenda: Relacionada a cada medique para obtener la informaciòn de los dìas y horarios en que atiende.
*Turno: Guardara los datos de los turnos, relacionando la informaciòn de mediques, pacientes y consultorios.
*Reprogramaciòn: 
*Error:
*Cobertura: Guardarà las obras sociales que atiende cada medique.
*Liquidaciòn cabecera:
*Liquidacion detalle:
*Envio email:


En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, las decisiones que se fueron tomando a lo largo
del trabajo práctico, y las cuestiones de diseño que consideren
importantes.

También, se puede incluir una descripción general del programa—cómo
funciona.

== Implementación

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde.

Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
breve descripción, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos.

También se puede incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.
